"""
BOS Permissions - Canonical Constants
=====================================
Deterministic constants for permission and grant scope semantics.
"""

PERMISSION_CMD_EXECUTE_GENERIC = "CMD_EXECUTE_GENERIC"
PERMISSION_ADMIN_CONFIGURE = "ADMIN_CONFIGURE"
PERMISSION_POS_SELL = "POS_SELL"
PERMISSION_CASH_MOVE = "CASH_MOVE"
PERMISSION_INVENTORY_MOVE = "INVENTORY_MOVE"
PERMISSION_DOC_ISSUE = "DOC_ISSUE"

SCOPE_GRANT_BUSINESS = "BUSINESS"
SCOPE_GRANT_BRANCH = "BRANCH"

GRANT_STATUS_ACTIVE = "ACTIVE"
GRANT_STATUS_INACTIVE = "INACTIVE"

VALID_SCOPE_TYPES = frozenset({SCOPE_GRANT_BUSINESS, SCOPE_GRANT_BRANCH})
VALID_GRANT_STATUSES = frozenset(
    {GRANT_STATUS_ACTIVE, GRANT_STATUS_INACTIVE}
)

VALID_PERMISSIONS = frozenset(
    {
        PERMISSION_CMD_EXECUTE_GENERIC,
        PERMISSION_ADMIN_CONFIGURE,
        PERMISSION_POS_SELL,
        PERMISSION_CASH_MOVE,
        PERMISSION_INVENTORY_MOVE,
        PERMISSION_DOC_ISSUE,
    }
)
