"""
BOS Permissions - Command to Permission Registry
================================================
"""

from __future__ import annotations

from core.permissions.constants import (
    PERMISSION_ADMIN_CONFIGURE,
    PERMISSION_CASH_MOVE,
    PERMISSION_CMD_EXECUTE_GENERIC,
    PERMISSION_DOC_ISSUE,
    PERMISSION_HR_MANAGE,
    PERMISSION_HOTEL_MANAGE,
    PERMISSION_INVENTORY_AUDIT,
    PERMISSION_INVENTORY_MOVE,
    PERMISSION_POS_SELL,
    PERMISSION_PROCUREMENT_APPROVE,
    PERMISSION_REPORTING_VIEW,
    PERMISSION_RESTAURANT_SERVE,
    PERMISSION_WORKSHOP_MANAGE,
)

COMMAND_PERMISSION_MAP = {
    # ------------------------------------------------------------------ Admin
    "admin.feature_flag.set.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.feature_flag.clear.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.compliance_profile.upsert.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.compliance_profile.deactivate.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.document_template.upsert.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.document_template.deactivate.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.api_key.create.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.api_key.revoke.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.api_key.rotate.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.api_key.list.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.identity.bootstrap.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.roles.assign.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.roles.revoke.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.roles.list.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.actors.list.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.actors.deactivate.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.business.read.request": PERMISSION_ADMIN_CONFIGURE,
    "admin.branches.list.request": PERMISSION_ADMIN_CONFIGURE,
    # ------------------------------------------------------------------ Documents
    "doc.receipt.issue.request": PERMISSION_DOC_ISSUE,
    "doc.quote.issue.request": PERMISSION_DOC_ISSUE,
    "doc.invoice.issue.request": PERMISSION_DOC_ISSUE,
    "doc.proforma_invoice.issue.request": PERMISSION_DOC_ISSUE,
    "doc.credit_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.debit_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.purchase_order.issue.request": PERMISSION_DOC_ISSUE,
    "doc.goods_receipt_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.delivery_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.sales_order.issue.request": PERMISSION_DOC_ISSUE,
    "doc.refund_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.work_order.issue.request": PERMISSION_DOC_ISSUE,
    "doc.cutting_list.issue.request": PERMISSION_DOC_ISSUE,
    "doc.completion_certificate.issue.request": PERMISSION_DOC_ISSUE,
    "doc.kitchen_order_ticket.issue.request": PERMISSION_DOC_ISSUE,
    "doc.folio.issue.request": PERMISSION_DOC_ISSUE,
    "doc.reservation_confirmation.issue.request": PERMISSION_DOC_ISSUE,
    "doc.registration_card.issue.request": PERMISSION_DOC_ISSUE,
    "doc.cancellation_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.payment_voucher.issue.request": PERMISSION_DOC_ISSUE,
    "doc.petty_cash_voucher.issue.request": PERMISSION_DOC_ISSUE,
    "doc.stock_transfer_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.stock_adjustment_note.issue.request": PERMISSION_DOC_ISSUE,
    "doc.statement.issue.request": PERMISSION_DOC_ISSUE,
    "doc.cash_session_reconciliation.issue.request": PERMISSION_DOC_ISSUE,
    "doc.material_requisition.issue.request": PERMISSION_DOC_ISSUE,
    "doc.job_sheet.issue.request": PERMISSION_DOC_ISSUE,
    # ------------------------------------------------------------------ Retail / POS
    "retail.sale.open.request": PERMISSION_POS_SELL,
    "retail.sale.add_line.request": PERMISSION_POS_SELL,
    "retail.sale.remove_line.request": PERMISSION_POS_SELL,
    "retail.sale.complete.request": PERMISSION_POS_SELL,
    "retail.sale.void.request": PERMISSION_POS_SELL,
    "retail.sale.apply_discount.request": PERMISSION_POS_SELL,
    "retail.refund.issue.request": PERMISSION_POS_SELL,
    "retail.cart.apply_promotion.request": PERMISSION_POS_SELL,
    # ------------------------------------------------------------------ Cash
    "cash.session.open.request": PERMISSION_CASH_MOVE,
    "cash.session.close.request": PERMISSION_CASH_MOVE,
    "cash.payment.record.request": PERMISSION_CASH_MOVE,
    "cash.deposit.record.request": PERMISSION_CASH_MOVE,
    "cash.withdrawal.record.request": PERMISSION_CASH_MOVE,
    # ------------------------------------------------------------------ Inventory
    "inventory.stock.move.request": PERMISSION_INVENTORY_MOVE,
    "inventory.stock.transfer.request": PERMISSION_INVENTORY_MOVE,
    "inventory.stock.issue.request": PERMISSION_INVENTORY_MOVE,
    "inventory.stock.receive.request": PERMISSION_INVENTORY_MOVE,
    "inventory.item.register.request": PERMISSION_INVENTORY_AUDIT,
    "inventory.item.update.request": PERMISSION_INVENTORY_AUDIT,
    "inventory.stock.adjust.request": PERMISSION_INVENTORY_AUDIT,
    # ------------------------------------------------------------------ Restaurant / Bar
    "restaurant.table.open.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.table.close.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.order.place.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.order.cancel.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.order.serve_item.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.bill.present.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.bill.settle.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.bill.split.request": PERMISSION_RESTAURANT_SERVE,
    "restaurant.kitchen.ticket.send.request": PERMISSION_RESTAURANT_SERVE,
    # ------------------------------------------------------------------ Workshop
    "workshop.job.create.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.job.assign.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.job.start.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.job.complete.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.job.invoice.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.quote.generate.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.quote.accept.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.quote.reject.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.project.quote.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.cutlist.generate.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.material.consume.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.offcut.record.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.style.register.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.style.update.request": PERMISSION_WORKSHOP_MANAGE,
    "workshop.style.deactivate.request": PERMISSION_WORKSHOP_MANAGE,
    # ------------------------------------------------------------------ Hotel
    "hotel.reservation.create.request": PERMISSION_HOTEL_MANAGE,
    "hotel.reservation.confirm.request": PERMISSION_HOTEL_MANAGE,
    "hotel.reservation.modify.request": PERMISSION_HOTEL_MANAGE,
    "hotel.reservation.cancel.request": PERMISSION_HOTEL_MANAGE,
    "hotel.reservation.no_show.request": PERMISSION_HOTEL_MANAGE,
    "hotel.guest.check_in.request": PERMISSION_HOTEL_MANAGE,
    "hotel.guest.check_out.request": PERMISSION_HOTEL_MANAGE,
    "hotel.stay.extend.request": PERMISSION_HOTEL_MANAGE,
    "hotel.early_departure.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.open.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.post_charge.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.receive_payment.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.settle.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.adjust.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.apply_credit.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.split.request": PERMISSION_HOTEL_MANAGE,
    "hotel.folio.transfer.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room.create.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room.change_status.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room.move.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room.set_out_of_order.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room.return_to_service.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room_type.define.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room_type.update.request": PERMISSION_HOTEL_MANAGE,
    "hotel.room_night.post_charge.request": PERMISSION_HOTEL_MANAGE,
    "hotel.rate_plan.create.request": PERMISSION_HOTEL_MANAGE,
    "hotel.rate_plan.update.request": PERMISSION_HOTEL_MANAGE,
    "hotel.rate_plan.deactivate.request": PERMISSION_HOTEL_MANAGE,
    "hotel.seasonal_rate.set.request": PERMISSION_HOTEL_MANAGE,
    "hotel.night_audit.run.request": PERMISSION_HOTEL_MANAGE,
    "hotel.property.configure.request": PERMISSION_HOTEL_MANAGE,
    "hotel.housekeeping.assign_task.request": PERMISSION_HOTEL_MANAGE,
    "hotel.housekeeping.start_task.request": PERMISSION_HOTEL_MANAGE,
    "hotel.housekeeping.complete_task.request": PERMISSION_HOTEL_MANAGE,
    "hotel.housekeeping.inspect_room.request": PERMISSION_HOTEL_MANAGE,
    "hotel.housekeeping.fail_inspection.request": PERMISSION_HOTEL_MANAGE,
    "hotel.lost_found.log.request": PERMISSION_HOTEL_MANAGE,
    "hotel.lost_found.claim.request": PERMISSION_HOTEL_MANAGE,
    "hotel.maintenance.resolve.request": PERMISSION_HOTEL_MANAGE,
    # ------------------------------------------------------------------ Procurement
    "procurement.requisition.create.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.requisition.approve.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.order.create.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.order.approve.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.order.receive.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.order.cancel.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.invoice.match.request": PERMISSION_PROCUREMENT_APPROVE,
    "procurement.payment.release.request": PERMISSION_PROCUREMENT_APPROVE,
    # ------------------------------------------------------------------ HR
    "hr.employee.onboard.request": PERMISSION_HR_MANAGE,
    "hr.employee.terminate.request": PERMISSION_HR_MANAGE,
    "hr.payroll.run.request": PERMISSION_HR_MANAGE,
    "hr.leave.request.request": PERMISSION_HR_MANAGE,
    "hr.shift.start.request": PERMISSION_HR_MANAGE,
    "hr.shift.end.request": PERMISSION_HR_MANAGE,
    # ------------------------------------------------------------------ Reporting
    "reporting.kpi.record.request": PERMISSION_REPORTING_VIEW,
    "reporting.report.generate.request": PERMISSION_REPORTING_VIEW,
    "reporting.snapshot.record.request": PERMISSION_REPORTING_VIEW,
    # ------------------------------------------------------------------ Accounting
    "accounting.account.create.request": PERMISSION_ADMIN_CONFIGURE,
    "accounting.journal.post.request": PERMISSION_ADMIN_CONFIGURE,
    "accounting.journal.reverse.request": PERMISSION_ADMIN_CONFIGURE,
    "accounting.obligation.create.request": PERMISSION_ADMIN_CONFIGURE,
    "accounting.obligation.fulfill.request": PERMISSION_ADMIN_CONFIGURE,
    "accounting.statement.generate.request": PERMISSION_ADMIN_CONFIGURE,
    "accounting.ar_aging.snapshot.request": PERMISSION_ADMIN_CONFIGURE,
    # ------------------------------------------------------------------ Loyalty / Wallet / Promotion / Customer
    "loyalty.program.configure.request": PERMISSION_ADMIN_CONFIGURE,
    "loyalty.points.earn.request": PERMISSION_POS_SELL,
    "loyalty.points.redeem.request": PERMISSION_POS_SELL,
    "loyalty.points.adjust.request": PERMISSION_ADMIN_CONFIGURE,
    "loyalty.points.expire.request": PERMISSION_ADMIN_CONFIGURE,
    "loyalty.points.reverse.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.policy.configure.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.credit.issue.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.credit.spend.request": PERMISSION_POS_SELL,
    "wallet.credit.reverse.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.credit.expire.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.credit.freeze.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.credit.unfreeze.request": PERMISSION_ADMIN_CONFIGURE,
    "wallet.credit.adjust.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.program.create.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.program.activate.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.program.deactivate.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.campaign.create.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.campaign.activate.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.campaign.deactivate.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.rule.add.request": PERMISSION_ADMIN_CONFIGURE,
    "promotion.coupon.issue.request": PERMISSION_POS_SELL,
    "promotion.coupon.redeem.request": PERMISSION_POS_SELL,
    "promotion.apply.request": PERMISSION_POS_SELL,
    "promotion.basket.evaluate.request": PERMISSION_POS_SELL,
    "promotion.credit_note.issue.request": PERMISSION_POS_SELL,
    "promotion.rebate.settle.request": PERMISSION_ADMIN_CONFIGURE,
    "customer.profile.create.request": PERMISSION_POS_SELL,
    "customer.profile.update.request": PERMISSION_POS_SELL,
    "customer.global.register.request": PERMISSION_POS_SELL,
    "customer.link.request.request": PERMISSION_POS_SELL,
    "customer.link.approve.request": PERMISSION_ADMIN_CONFIGURE,
    "customer.link.revoke.request": PERMISSION_ADMIN_CONFIGURE,
    "customer.segment.assign.request": PERMISSION_ADMIN_CONFIGURE,
    "customer.consent.update_scope.request": PERMISSION_POS_SELL,
    # ------------------------------------------------------------------ Cart QR / QR Menu
    "cart_qr.create.request": PERMISSION_POS_SELL,
    "cart_qr.item.add.request": PERMISSION_POS_SELL,
    "cart_qr.item.remove.request": PERMISSION_POS_SELL,
    "cart_qr.publish.request": PERMISSION_POS_SELL,
    "cart_qr.selection.receive.request": PERMISSION_POS_SELL,
    "cart_qr.transfer_to_pos.request": PERMISSION_POS_SELL,
    "cart_qr.cancel.request": PERMISSION_POS_SELL,
    "cart_qr.expire.request": PERMISSION_POS_SELL,
    "qr_menu.register.request": PERMISSION_ADMIN_CONFIGURE,
    "qr_menu.session.create.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.session.expire.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.item.order.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.item.remove.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.order.submit.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.order.accept.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.order.reject.request": PERMISSION_RESTAURANT_SERVE,
    "qr_menu.order.clarify.request": PERMISSION_RESTAURANT_SERVE,
    # ------------------------------------------------------------------ Test
    "test.thing.do.request": PERMISSION_CMD_EXECUTE_GENERIC,
    "test.x.y.request": PERMISSION_CMD_EXECUTE_GENERIC,
}


def resolve_required_permission(command_type: str) -> str | None:
    """Resolve required permission for a command type."""
    return COMMAND_PERMISSION_MAP.get(command_type)
