"""
BOS Django adapter URL routing.
"""

from django.urls import path

from adapters.django_api import views


urlpatterns = [
    path("admin/business", views.business_profile_view),
    path("admin/branches", views.branches_list_view),
    path("admin/feature-flags", views.feature_flags_list_view),
    path("admin/compliance-profiles", views.compliance_profiles_list_view),
    path("admin/document-templates", views.document_templates_list_view),
    path("docs", views.issued_documents_list_view),
    path("admin/api-keys", views.api_keys_list_view),
    path("admin/roles", views.roles_list_view),
    path("admin/actors", views.actors_list_view),
    path("admin/feature-flags/set", views.feature_flags_set_view),
    path("admin/feature-flags/clear", views.feature_flags_clear_view),
    path("admin/api-keys/create", views.api_keys_create_view),
    path("admin/api-keys/revoke", views.api_keys_revoke_view),
    path("admin/api-keys/rotate", views.api_keys_rotate_view),
    path("admin/identity/bootstrap", views.identity_bootstrap_view),
    path("admin/roles/assign", views.roles_assign_view),
    path("admin/roles/revoke", views.roles_revoke_view),
    path("admin/actors/deactivate", views.actors_deactivate_view),
    path("admin/compliance-profiles/upsert", views.compliance_profiles_upsert_view),
    path(
        "admin/compliance-profiles/deactivate",
        views.compliance_profiles_deactivate_view,
    ),
    path("admin/document-templates/upsert", views.document_templates_upsert_view),
    path(
        "admin/document-templates/deactivate",
        views.document_templates_deactivate_view,
    ),
    # Tax rule configuration
    path("admin/tax-rules", views.tax_rules_list_view),
    path("admin/tax-rules/set", views.tax_rules_set_view),
    # Business profile update
    path("admin/business/update", views.business_update_view),
    # Custom role creation
    path("admin/roles/create", views.roles_create_view),
    # Customer profile CRUD
    path("admin/customers", views.customers_list_view),
    path("admin/customers/create", views.customers_create_view),
    path("admin/customers/update", views.customers_update_view),
    path("docs/receipt/issue", views.issue_receipt_view),
    path("docs/quote/issue", views.issue_quote_view),
    path("docs/invoice/issue", views.issue_invoice_view),
    # Generic document issue endpoint — handles all 25 document types
    # Must come AFTER the specific paths above to avoid shadowing them
    path("docs/<str:doc_type>/issue", views.issue_document_type_view),
    # Phase 3: render & verification
    path("docs/<uuid:document_id>/render-plan", views.document_render_plan_view),
    path("docs/<uuid:document_id>/render-html", views.document_render_html_view),
    path("docs/<uuid:document_id>/render-pdf", views.document_render_pdf_view),
    path("docs/<uuid:document_id>/verify", views.document_verify_view),
    # Data Migration ("Hamisha Data") endpoints
    path("admin/migration/create-job", views.migration_create_job_view),
    path("admin/migration/upload", views.migration_upload_view),
    path("admin/migration/complete", views.migration_complete_view),
    path("admin/migration/cancel", views.migration_cancel_view),
    path("admin/migration/jobs", views.migration_jobs_list_view),
    path("admin/migration/mappings", views.migration_mappings_view),
    # SaaS — Engine Combos & Pricing
    path("saas/engines", views.saas_engines_list_view),
    path("saas/engines/register", views.saas_register_engine_view),
    path("saas/combos", views.saas_combos_list_view),
    path("saas/combos/define", views.saas_define_combo_view),
    path("saas/combos/update", views.saas_update_combo_view),
    path("saas/combos/deactivate", views.saas_deactivate_combo_view),
    path("saas/combos/set-rate", views.saas_set_combo_rate_view),
    path("saas/pricing", views.saas_pricing_catalog_view),
    # SaaS — Trial Policy & Agreements
    path("saas/trial-policy", views.saas_trial_policy_view),
    path("saas/trial-policy/set", views.saas_set_trial_policy_view),
    path("saas/trials/create", views.saas_create_trial_view),
    path("saas/trials/extend", views.saas_extend_trial_view),
    path("saas/trials/convert", views.saas_convert_trial_view),
    path("saas/trials/agreement", views.saas_trial_agreement_view),
    # SaaS — Rate Governance
    path("saas/rates/publish-change", views.saas_publish_rate_change_view),
    path("saas/rates/effective", views.saas_effective_rate_view),
    # SaaS — Promotions
    path("saas/promos", views.saas_promos_list_view),
    path("saas/promos/create", views.saas_create_promo_view),
    path("saas/promos/redeem", views.saas_redeem_promo_view),
    # SaaS — Referrals ("Alika Rafiki")
    path("saas/referrals/set-policy", views.saas_set_referral_policy_view),
    path("saas/referrals/generate-code", views.saas_generate_referral_code_view),
    path("saas/referrals/submit", views.saas_submit_referral_view),
    path("saas/referrals/qualify", views.saas_qualify_referral_view),
    # SaaS — Resellers ("Wakala wa BOS")
    path("saas/resellers", views.saas_resellers_list_view),
    path("saas/resellers/register", views.saas_register_reseller_view),
    path("saas/resellers/update", views.saas_update_reseller_view),
    path("saas/resellers/suspend", views.saas_suspend_reseller_view),
    path("saas/resellers/reinstate", views.saas_reinstate_reseller_view),
    path("saas/resellers/terminate", views.saas_terminate_reseller_view),
    path("saas/resellers/link-tenant", views.saas_link_tenant_view),
    path("saas/resellers/accrue-commission", views.saas_accrue_commission_view),
    path("saas/resellers/request-payout", views.saas_request_payout_view),
    path("saas/resellers/approve-payout", views.saas_approve_payout_view),
    path("saas/resellers/reject-payout", views.saas_reject_payout_view),
    path("saas/resellers/payouts", views.saas_payouts_list_view),
    path("saas/resellers/assign-territory", views.saas_assign_territory_view),
    path("saas/resellers/revoke-territory", views.saas_revoke_territory_view),
    path("saas/resellers/transfer", views.saas_transfer_reseller_view),
    path("saas/resellers/<str:reseller_id>", views.saas_reseller_detail_view),
    # SaaS — Regional Management
    path("saas/regions/managers", views.saas_regional_managers_list_view),
    path("saas/regions/appoint-manager", views.saas_appoint_regional_manager_view),
    path("saas/regions/remove-manager", views.saas_remove_regional_manager_view),
    path("saas/regions/set-commission-override", views.saas_set_commission_override_view),
    path("saas/regions/commission-overrides", views.saas_commission_overrides_list_view),
    path("saas/regions/set-target", views.saas_set_regional_target_view),
    path("saas/regions/targets", views.saas_regional_targets_list_view),
    path("saas/regions/<str:region_code>/resellers", views.saas_region_resellers_view),
    path("saas/regions/<str:region_code>/performance", views.saas_region_performance_view),
    path("saas/regions/<str:region_code>/summary", views.saas_region_summary_view),
    path("saas/regions/<str:region_code>/territories", views.saas_region_territories_view),
    # SaaS — Region Lifecycle & Financial Administration
    path("saas/regions/launch", views.saas_region_launch_view),
    path("saas/regions/suspend", views.saas_region_suspend_view),
    path("saas/regions/reactivate", views.saas_region_reactivate_view),
    path("saas/regions/sunset", views.saas_region_sunset_view),
    path("saas/regions/set-payment-channel", views.saas_region_set_payment_channel_view),
    path("saas/regions/remove-payment-channel", views.saas_region_remove_payment_channel_view),
    path("saas/regions/set-settlement", views.saas_region_set_settlement_view),
    path("saas/regions/<str:region_code>/detail", views.saas_region_detail_view),
    path("saas/regions/<str:region_code>/payment-channels", views.saas_region_payment_channels_view),
    path("saas/regions/<str:region_code>/settlement-accounts", views.saas_region_settlement_accounts_view),
    path("saas/regions/<str:region_code>/dashboard", views.saas_region_dashboard_view),
    # SaaS — Subscriptions
    path("saas/subscriptions", views.saas_subscription_view),
    path("saas/subscriptions/start-trial", views.saas_start_trial_sub_view),
    path("saas/subscriptions/activate", views.saas_activate_sub_view),
    path("saas/subscriptions/cancel", views.saas_cancel_sub_view),
    path("saas/subscriptions/change-combo", views.saas_change_combo_view),
    # SaaS — Tenant Plan Builder (self-service)
    path("saas/tenant/available-plans", views.saas_tenant_available_plans_view),
    path("saas/tenant/my-plan", views.saas_tenant_my_plan_view),
    path("saas/tenant/select-plan", views.saas_tenant_select_plan_view),
    # SaaS — Service-Based Pricing (Regions, Services, Capacity, Reductions)
    path("saas/regions", views.saas_regions_list_view),
    path("saas/regions/add", views.saas_regions_add_view),
    path("saas/regions/update", views.saas_regions_update_view),
    path("saas/services", views.saas_services_list_view),
    path("saas/services/set-rate", views.saas_services_set_rate_view),
    path("saas/services/toggle", views.saas_services_toggle_view),
    path("saas/capacity", views.saas_capacity_list_view),
    path("saas/capacity/set-rate", views.saas_capacity_set_rate_view),
    path("saas/reductions", views.saas_reductions_list_view),
    path("saas/reductions/set", views.saas_reductions_set_view),
    path("saas/calculate-price", views.saas_calculate_price_view),
    # SaaS — Compliance Packs (Versioned)
    path("saas/compliance-packs", views.saas_compliance_packs_list_view),
    path("saas/compliance-packs/publish", views.saas_publish_compliance_pack_view),
    path("saas/compliance-packs/deprecate", views.saas_deprecate_compliance_pack_view),
    path("saas/compliance-packs/pin-tenant", views.saas_pin_tenant_pack_view),
    path("saas/compliance-packs/upgrade-tenant", views.saas_upgrade_tenant_pack_view),
    path("saas/compliance-packs/<str:region_code>/latest", views.saas_compliance_pack_latest_view),
    path("saas/compliance-packs/<str:region_code>/<int:version>", views.saas_compliance_pack_detail_view),
    # SaaS — Tenant Compliance Onboarding
    path("saas/compliance/set-country-policy", views.saas_set_country_policy_view),
    path("saas/compliance/country-policies", views.saas_country_policies_list_view),
    path("saas/compliance/submit-profile", views.saas_submit_compliance_profile_view),
    path("saas/compliance/review-profile", views.saas_review_compliance_profile_view),
    path("saas/compliance/activate-profile", views.saas_activate_compliance_profile_view),
    path("saas/compliance/suspend-profile", views.saas_suspend_compliance_profile_view),
    path("saas/compliance/reactivate-profile", views.saas_reactivate_compliance_profile_view),
    path("saas/compliance/profile", views.saas_compliance_profile_view),
    # Platform Audit Log (ACMV — Audit)
    path("platform/audit", views.platform_audit_list_view),
    path("platform/audit/<str:entry_id>", views.platform_audit_entry_view),
    path("platform/audit/tenant/<str:tenant_id>", views.platform_audit_tenant_history_view),
    # Platform Health / Observability (ACMV — Monitoring)
    path("platform/health", views.platform_health_view),
    path("platform/health/slos", views.platform_health_slos_view),
    path("platform/health/breaches", views.platform_health_breaches_view),
    path("platform/health/snapshot", views.platform_health_snapshot_view),
    # Compliance Review Queue (ACMV — Compliance / Verification)
    path("platform/compliance/pending", views.platform_compliance_pending_view),
    path("platform/compliance/stats", views.platform_compliance_stats_view),
    # Governance (Two-Level Admin Model)
    path("platform/compliance/audit", views.platform_compliance_audit_view),
    path("platform/governance/agents", views.platform_governance_agents_view),
    path("platform/governance/escalations", views.platform_governance_escalations_view),
    # ── Unified Agent Management ─────────────────────────────────────────────
    path("saas/agents", views.saas_agents_list_view),
    path("saas/agents/register", views.saas_agents_register_view),
    path("saas/agents/update", views.saas_agents_update_view),
    path("saas/agents/suspend", views.saas_agents_suspend_view),
    path("saas/agents/reinstate", views.saas_agents_reinstate_view),
    path("saas/agents/terminate", views.saas_agents_terminate_view),
    path("saas/agents/link-tenant", views.saas_agents_link_tenant_view),
    path("saas/agents/accrue-commission", views.saas_agents_accrue_commission_view),
    path("saas/agents/payouts", views.saas_agents_payouts_view),
    path("saas/agents/payouts/approve", views.saas_agents_approve_payout_view),
    path("saas/agents/payouts/reject", views.saas_agents_reject_payout_view),
    path("saas/agents/commission-ranges", views.saas_agents_commission_ranges_view),
    path("saas/agents/commission-ranges/set", views.saas_agents_commission_ranges_set_view),
    path("saas/agents/grant-governance", views.saas_agents_grant_governance_view),
    path("saas/agents/revoke-governance", views.saas_agents_revoke_governance_view),
    path("saas/agents/escalations/create", views.saas_agents_create_escalation_view),
    path("saas/agents/escalations/resolve", views.saas_agents_resolve_escalation_view),
    path("saas/agents/<str:agent_id>", views.saas_agents_detail_view),
    # ── Discount Governance ──────────────────────────────────────────────────
    path("saas/discount-governance", views.saas_discount_governance_view),
    path("saas/discount-governance/set", views.saas_discount_governance_set_view),
    path("saas/agents/rla-discount-settings", views.saas_rla_discount_settings_view),
    # ── Revenue Ledger ───────────────────────────────────────────────────────
    path("saas/ledger/entries", views.saas_ledger_entries_view),
    path("saas/ledger/entry/<str:entry_id>", views.saas_ledger_entry_detail_view),
    path("saas/ledger/record-sale", views.saas_ledger_record_sale_view),
    path("saas/ledger/reverse", views.saas_ledger_reverse_view),
    path("saas/ledger/settle", views.saas_ledger_settle_view),
    path("saas/ledger/summary", views.saas_ledger_summary_view),
    path("saas/ledger/rules", views.saas_ledger_rules_view),
    path("saas/ledger/rules/set", views.saas_ledger_rules_set_view),
    path("saas/ledger/operating-laws", views.saas_ledger_operating_laws_view),
    # ── Platform Admin Management ────────────────────────────────────────────
    path("platform/me", views.platform_me_view),
    path("platform/admins", views.platform_admins_list_view),
    path("platform/admins/add", views.platform_admin_add_view),
    path("platform/admins/update-role", views.platform_admin_update_role_view),
    path("platform/admins/suspend", views.platform_admin_suspend_view),
    path("platform/admins/reinstate", views.platform_admin_reinstate_view),
    # ── Platform Regional Rollup ─────────────────────────────────────────────
    path("platform/regions/rollup", views.platform_regions_rollup_view),
    # ── Platform Remittance Oversight ────────────────────────────────────────
    path("platform/remittance/overdue", views.platform_remittance_overdue_view),
    # ── Agent Contract (Franchise Agreement) ────────────────────────────────
    path("saas/agents/contract/generate", views.agent_contract_generate_view),
    path("saas/agents/contract/sign", views.agent_contract_sign_view),
    path("saas/agents/contract", views.agent_contract_get_view),
    path("saas/agents/terminate-reversible", views.agent_terminate_reversible_view),
    path("saas/agents/terminate-permanent", views.agent_terminate_permanent_view),
    path("saas/agents/reinstate-full", views.agent_reinstate_full_view),
    path("saas/agents/reinstate-reduced", views.agent_reinstate_reduced_view),
    # ── Pending-RLA Regions (tenants on continuity hold) ────────────────────
    path("saas/regions/pending-rla", views.agent_pending_regions_view),
]
