"""
BOS Document Issuance - Command/Event Registry
==============================================
"""

from __future__ import annotations

from core.documents.models import (
    DOCUMENT_CANCELLATION_NOTE,
    DOCUMENT_COMPLETION_CERTIFICATE,
    DOCUMENT_CREDIT_NOTE,
    DOCUMENT_CUTTING_LIST,
    DOCUMENT_DEBIT_NOTE,
    DOCUMENT_DELIVERY_NOTE,
    DOCUMENT_FOLIO,
    DOCUMENT_GOODS_RECEIPT_NOTE,
    DOCUMENT_INVOICE,
    DOCUMENT_KITCHEN_ORDER_TICKET,
    DOCUMENT_MATERIAL_REQUISITION,
    DOCUMENT_PAYMENT_VOUCHER,
    DOCUMENT_PETTY_CASH_VOUCHER,
    DOCUMENT_PROFORMA_INVOICE,
    DOCUMENT_PURCHASE_ORDER,
    DOCUMENT_QUOTE,
    DOCUMENT_RECEIPT,
    DOCUMENT_REFUND_NOTE,
    DOCUMENT_REGISTRATION_CARD,
    DOCUMENT_RESERVATION_CONFIRMATION,
    DOCUMENT_SALES_ORDER,
    DOCUMENT_STATEMENT,
    DOCUMENT_STOCK_ADJUSTMENT_NOTE,
    DOCUMENT_STOCK_TRANSFER_NOTE,
    DOCUMENT_WORK_ORDER,
)

# ── Issue request command types ───────────────────────────────────────────────
DOC_RECEIPT_ISSUE_REQUEST                  = "doc.receipt.issue.request"
DOC_QUOTE_ISSUE_REQUEST                    = "doc.quote.issue.request"
DOC_INVOICE_ISSUE_REQUEST                  = "doc.invoice.issue.request"
DOC_PROFORMA_INVOICE_ISSUE_REQUEST         = "doc.proforma_invoice.issue.request"
DOC_DELIVERY_NOTE_ISSUE_REQUEST            = "doc.delivery_note.issue.request"
DOC_CREDIT_NOTE_ISSUE_REQUEST              = "doc.credit_note.issue.request"
DOC_DEBIT_NOTE_ISSUE_REQUEST               = "doc.debit_note.issue.request"
DOC_PURCHASE_ORDER_ISSUE_REQUEST           = "doc.purchase_order.issue.request"
DOC_GOODS_RECEIPT_NOTE_ISSUE_REQUEST       = "doc.goods_receipt_note.issue.request"
DOC_SALES_ORDER_ISSUE_REQUEST              = "doc.sales_order.issue.request"
DOC_REFUND_NOTE_ISSUE_REQUEST              = "doc.refund_note.issue.request"
DOC_WORK_ORDER_ISSUE_REQUEST               = "doc.work_order.issue.request"
DOC_MATERIAL_REQUISITION_ISSUE_REQUEST     = "doc.material_requisition.issue.request"
DOC_CUTTING_LIST_ISSUE_REQUEST             = "doc.cutting_list.issue.request"
DOC_COMPLETION_CERTIFICATE_ISSUE_REQUEST   = "doc.completion_certificate.issue.request"
DOC_KITCHEN_ORDER_TICKET_ISSUE_REQUEST     = "doc.kitchen_order_ticket.issue.request"
DOC_FOLIO_ISSUE_REQUEST                    = "doc.folio.issue.request"
DOC_RESERVATION_CONFIRMATION_ISSUE_REQUEST = "doc.reservation_confirmation.issue.request"
DOC_REGISTRATION_CARD_ISSUE_REQUEST        = "doc.registration_card.issue.request"
DOC_CANCELLATION_NOTE_ISSUE_REQUEST        = "doc.cancellation_note.issue.request"
DOC_PAYMENT_VOUCHER_ISSUE_REQUEST          = "doc.payment_voucher.issue.request"
DOC_PETTY_CASH_VOUCHER_ISSUE_REQUEST       = "doc.petty_cash_voucher.issue.request"
DOC_STOCK_TRANSFER_NOTE_ISSUE_REQUEST      = "doc.stock_transfer_note.issue.request"
DOC_STOCK_ADJUSTMENT_NOTE_ISSUE_REQUEST    = "doc.stock_adjustment_note.issue.request"
DOC_STATEMENT_ISSUE_REQUEST                = "doc.statement.issue.request"

# ── Issued event types ────────────────────────────────────────────────────────
DOC_RECEIPT_ISSUED_V1                      = "doc.receipt.issued.v1"
DOC_QUOTE_ISSUED_V1                        = "doc.quote.issued.v1"
DOC_INVOICE_ISSUED_V1                      = "doc.invoice.issued.v1"
DOC_PROFORMA_INVOICE_ISSUED_V1             = "doc.proforma_invoice.issued.v1"
DOC_DELIVERY_NOTE_ISSUED_V1                = "doc.delivery_note.issued.v1"
DOC_CREDIT_NOTE_ISSUED_V1                  = "doc.credit_note.issued.v1"
DOC_DEBIT_NOTE_ISSUED_V1                   = "doc.debit_note.issued.v1"
DOC_PURCHASE_ORDER_ISSUED_V1               = "doc.purchase_order.issued.v1"
DOC_GOODS_RECEIPT_NOTE_ISSUED_V1           = "doc.goods_receipt_note.issued.v1"
DOC_SALES_ORDER_ISSUED_V1                  = "doc.sales_order.issued.v1"
DOC_REFUND_NOTE_ISSUED_V1                  = "doc.refund_note.issued.v1"
DOC_WORK_ORDER_ISSUED_V1                   = "doc.work_order.issued.v1"
DOC_MATERIAL_REQUISITION_ISSUED_V1         = "doc.material_requisition.issued.v1"
DOC_CUTTING_LIST_ISSUED_V1                 = "doc.cutting_list.issued.v1"
DOC_COMPLETION_CERTIFICATE_ISSUED_V1       = "doc.completion_certificate.issued.v1"
DOC_KITCHEN_ORDER_TICKET_ISSUED_V1         = "doc.kitchen_order_ticket.issued.v1"
DOC_FOLIO_ISSUED_V1                        = "doc.folio.issued.v1"
DOC_RESERVATION_CONFIRMATION_ISSUED_V1     = "doc.reservation_confirmation.issued.v1"
DOC_REGISTRATION_CARD_ISSUED_V1            = "doc.registration_card.issued.v1"
DOC_CANCELLATION_NOTE_ISSUED_V1            = "doc.cancellation_note.issued.v1"
DOC_PAYMENT_VOUCHER_ISSUED_V1              = "doc.payment_voucher.issued.v1"
DOC_PETTY_CASH_VOUCHER_ISSUED_V1           = "doc.petty_cash_voucher.issued.v1"
DOC_STOCK_TRANSFER_NOTE_ISSUED_V1          = "doc.stock_transfer_note.issued.v1"
DOC_STOCK_ADJUSTMENT_NOTE_ISSUED_V1        = "doc.stock_adjustment_note.issued.v1"
DOC_STATEMENT_ISSUED_V1                    = "doc.statement.issued.v1"

DOCUMENT_ISSUANCE_COMMAND_TYPES = frozenset({
    DOC_RECEIPT_ISSUE_REQUEST,
    DOC_QUOTE_ISSUE_REQUEST,
    DOC_INVOICE_ISSUE_REQUEST,
    DOC_PROFORMA_INVOICE_ISSUE_REQUEST,
    DOC_DELIVERY_NOTE_ISSUE_REQUEST,
    DOC_CREDIT_NOTE_ISSUE_REQUEST,
    DOC_DEBIT_NOTE_ISSUE_REQUEST,
    DOC_PURCHASE_ORDER_ISSUE_REQUEST,
    DOC_GOODS_RECEIPT_NOTE_ISSUE_REQUEST,
    DOC_SALES_ORDER_ISSUE_REQUEST,
    DOC_REFUND_NOTE_ISSUE_REQUEST,
    DOC_WORK_ORDER_ISSUE_REQUEST,
    DOC_MATERIAL_REQUISITION_ISSUE_REQUEST,
    DOC_CUTTING_LIST_ISSUE_REQUEST,
    DOC_COMPLETION_CERTIFICATE_ISSUE_REQUEST,
    DOC_KITCHEN_ORDER_TICKET_ISSUE_REQUEST,
    DOC_FOLIO_ISSUE_REQUEST,
    DOC_RESERVATION_CONFIRMATION_ISSUE_REQUEST,
    DOC_REGISTRATION_CARD_ISSUE_REQUEST,
    DOC_CANCELLATION_NOTE_ISSUE_REQUEST,
    DOC_PAYMENT_VOUCHER_ISSUE_REQUEST,
    DOC_PETTY_CASH_VOUCHER_ISSUE_REQUEST,
    DOC_STOCK_TRANSFER_NOTE_ISSUE_REQUEST,
    DOC_STOCK_ADJUSTMENT_NOTE_ISSUE_REQUEST,
    DOC_STATEMENT_ISSUE_REQUEST,
})

DOCUMENT_ISSUANCE_EVENT_TYPES = frozenset({
    DOC_RECEIPT_ISSUED_V1,
    DOC_QUOTE_ISSUED_V1,
    DOC_INVOICE_ISSUED_V1,
    DOC_PROFORMA_INVOICE_ISSUED_V1,
    DOC_DELIVERY_NOTE_ISSUED_V1,
    DOC_CREDIT_NOTE_ISSUED_V1,
    DOC_DEBIT_NOTE_ISSUED_V1,
    DOC_PURCHASE_ORDER_ISSUED_V1,
    DOC_GOODS_RECEIPT_NOTE_ISSUED_V1,
    DOC_SALES_ORDER_ISSUED_V1,
    DOC_REFUND_NOTE_ISSUED_V1,
    DOC_WORK_ORDER_ISSUED_V1,
    DOC_MATERIAL_REQUISITION_ISSUED_V1,
    DOC_CUTTING_LIST_ISSUED_V1,
    DOC_COMPLETION_CERTIFICATE_ISSUED_V1,
    DOC_KITCHEN_ORDER_TICKET_ISSUED_V1,
    DOC_FOLIO_ISSUED_V1,
    DOC_RESERVATION_CONFIRMATION_ISSUED_V1,
    DOC_REGISTRATION_CARD_ISSUED_V1,
    DOC_CANCELLATION_NOTE_ISSUED_V1,
    DOC_PAYMENT_VOUCHER_ISSUED_V1,
    DOC_PETTY_CASH_VOUCHER_ISSUED_V1,
    DOC_STOCK_TRANSFER_NOTE_ISSUED_V1,
    DOC_STOCK_ADJUSTMENT_NOTE_ISSUED_V1,
    DOC_STATEMENT_ISSUED_V1,
})

_COMMAND_DOC_TYPE_MAP = {
    DOC_RECEIPT_ISSUE_REQUEST:                  DOCUMENT_RECEIPT,
    DOC_QUOTE_ISSUE_REQUEST:                    DOCUMENT_QUOTE,
    DOC_INVOICE_ISSUE_REQUEST:                  DOCUMENT_INVOICE,
    DOC_PROFORMA_INVOICE_ISSUE_REQUEST:         DOCUMENT_PROFORMA_INVOICE,
    DOC_DELIVERY_NOTE_ISSUE_REQUEST:            DOCUMENT_DELIVERY_NOTE,
    DOC_CREDIT_NOTE_ISSUE_REQUEST:              DOCUMENT_CREDIT_NOTE,
    DOC_DEBIT_NOTE_ISSUE_REQUEST:               DOCUMENT_DEBIT_NOTE,
    DOC_PURCHASE_ORDER_ISSUE_REQUEST:           DOCUMENT_PURCHASE_ORDER,
    DOC_GOODS_RECEIPT_NOTE_ISSUE_REQUEST:       DOCUMENT_GOODS_RECEIPT_NOTE,
    DOC_SALES_ORDER_ISSUE_REQUEST:              DOCUMENT_SALES_ORDER,
    DOC_REFUND_NOTE_ISSUE_REQUEST:              DOCUMENT_REFUND_NOTE,
    DOC_WORK_ORDER_ISSUE_REQUEST:               DOCUMENT_WORK_ORDER,
    DOC_MATERIAL_REQUISITION_ISSUE_REQUEST:     DOCUMENT_MATERIAL_REQUISITION,
    DOC_CUTTING_LIST_ISSUE_REQUEST:             DOCUMENT_CUTTING_LIST,
    DOC_COMPLETION_CERTIFICATE_ISSUE_REQUEST:   DOCUMENT_COMPLETION_CERTIFICATE,
    DOC_KITCHEN_ORDER_TICKET_ISSUE_REQUEST:     DOCUMENT_KITCHEN_ORDER_TICKET,
    DOC_FOLIO_ISSUE_REQUEST:                    DOCUMENT_FOLIO,
    DOC_RESERVATION_CONFIRMATION_ISSUE_REQUEST: DOCUMENT_RESERVATION_CONFIRMATION,
    DOC_REGISTRATION_CARD_ISSUE_REQUEST:        DOCUMENT_REGISTRATION_CARD,
    DOC_CANCELLATION_NOTE_ISSUE_REQUEST:        DOCUMENT_CANCELLATION_NOTE,
    DOC_PAYMENT_VOUCHER_ISSUE_REQUEST:          DOCUMENT_PAYMENT_VOUCHER,
    DOC_PETTY_CASH_VOUCHER_ISSUE_REQUEST:       DOCUMENT_PETTY_CASH_VOUCHER,
    DOC_STOCK_TRANSFER_NOTE_ISSUE_REQUEST:      DOCUMENT_STOCK_TRANSFER_NOTE,
    DOC_STOCK_ADJUSTMENT_NOTE_ISSUE_REQUEST:    DOCUMENT_STOCK_ADJUSTMENT_NOTE,
    DOC_STATEMENT_ISSUE_REQUEST:                DOCUMENT_STATEMENT,
}

_COMMAND_EVENT_TYPE_MAP = {
    DOC_RECEIPT_ISSUE_REQUEST:                  DOC_RECEIPT_ISSUED_V1,
    DOC_QUOTE_ISSUE_REQUEST:                    DOC_QUOTE_ISSUED_V1,
    DOC_INVOICE_ISSUE_REQUEST:                  DOC_INVOICE_ISSUED_V1,
    DOC_PROFORMA_INVOICE_ISSUE_REQUEST:         DOC_PROFORMA_INVOICE_ISSUED_V1,
    DOC_DELIVERY_NOTE_ISSUE_REQUEST:            DOC_DELIVERY_NOTE_ISSUED_V1,
    DOC_CREDIT_NOTE_ISSUE_REQUEST:              DOC_CREDIT_NOTE_ISSUED_V1,
    DOC_DEBIT_NOTE_ISSUE_REQUEST:               DOC_DEBIT_NOTE_ISSUED_V1,
    DOC_PURCHASE_ORDER_ISSUE_REQUEST:           DOC_PURCHASE_ORDER_ISSUED_V1,
    DOC_GOODS_RECEIPT_NOTE_ISSUE_REQUEST:       DOC_GOODS_RECEIPT_NOTE_ISSUED_V1,
    DOC_SALES_ORDER_ISSUE_REQUEST:              DOC_SALES_ORDER_ISSUED_V1,
    DOC_REFUND_NOTE_ISSUE_REQUEST:              DOC_REFUND_NOTE_ISSUED_V1,
    DOC_WORK_ORDER_ISSUE_REQUEST:               DOC_WORK_ORDER_ISSUED_V1,
    DOC_MATERIAL_REQUISITION_ISSUE_REQUEST:     DOC_MATERIAL_REQUISITION_ISSUED_V1,
    DOC_CUTTING_LIST_ISSUE_REQUEST:             DOC_CUTTING_LIST_ISSUED_V1,
    DOC_COMPLETION_CERTIFICATE_ISSUE_REQUEST:   DOC_COMPLETION_CERTIFICATE_ISSUED_V1,
    DOC_KITCHEN_ORDER_TICKET_ISSUE_REQUEST:     DOC_KITCHEN_ORDER_TICKET_ISSUED_V1,
    DOC_FOLIO_ISSUE_REQUEST:                    DOC_FOLIO_ISSUED_V1,
    DOC_RESERVATION_CONFIRMATION_ISSUE_REQUEST: DOC_RESERVATION_CONFIRMATION_ISSUED_V1,
    DOC_REGISTRATION_CARD_ISSUE_REQUEST:        DOC_REGISTRATION_CARD_ISSUED_V1,
    DOC_CANCELLATION_NOTE_ISSUE_REQUEST:        DOC_CANCELLATION_NOTE_ISSUED_V1,
    DOC_PAYMENT_VOUCHER_ISSUE_REQUEST:          DOC_PAYMENT_VOUCHER_ISSUED_V1,
    DOC_PETTY_CASH_VOUCHER_ISSUE_REQUEST:       DOC_PETTY_CASH_VOUCHER_ISSUED_V1,
    DOC_STOCK_TRANSFER_NOTE_ISSUE_REQUEST:      DOC_STOCK_TRANSFER_NOTE_ISSUED_V1,
    DOC_STOCK_ADJUSTMENT_NOTE_ISSUE_REQUEST:    DOC_STOCK_ADJUSTMENT_NOTE_ISSUED_V1,
    DOC_STATEMENT_ISSUE_REQUEST:                DOC_STATEMENT_ISSUED_V1,
}


def is_document_issue_command_type(command_type: str) -> bool:
    return command_type in DOCUMENT_ISSUANCE_COMMAND_TYPES


def is_document_issuance_event_type(event_type: str) -> bool:
    return event_type in DOCUMENT_ISSUANCE_EVENT_TYPES


def resolve_doc_type_for_issue_command(command_type: str) -> str | None:
    return _COMMAND_DOC_TYPE_MAP.get(command_type)


def resolve_event_type_for_issue_command(command_type: str) -> str | None:
    return _COMMAND_EVENT_TYPE_MAP.get(command_type)


def register_document_issuance_event_types(event_type_registry) -> None:
    for event_type in sorted(DOCUMENT_ISSUANCE_EVENT_TYPES):
        event_type_registry.register(event_type)
