# Generated by Django 6.0.2 on 2026-02-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_name', models.CharField(help_text='Name of the projection being rebuilt.', max_length=255)),
                ('business_id', models.UUIDField(blank=True, help_text='Business scope. Null = full system replay.', null=True)),
                ('last_event_id', models.UUIDField(help_text='Last successfully processed event_id.')),
                ('last_received_at', models.DateTimeField(help_text='received_at of last processed event (for ordering).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this checkpoint was last saved.')),
            ],
            options={
                'db_table': 'replay_checkpoints',
                'indexes': [models.Index(fields=['projection_name', 'business_id'], name='idx_replay_proj_biz')],
                'unique_together': {('projection_name', 'business_id')},
            },
        ),
    ]
